finish task 4
li-wang-uk/Nc-news-project pull request #4
Opened 2023-11-20 16:42 UTC by li-wang-uk

2023-11-20 16:50 UTC, nc-verity-gregory requested changes
I need you to look at this again, your model is leaving you open to vulnerabilities and your test is not specific enough. Please make the changes and resubmit your PR.

2023-11-20 16:50 UTC, nc-verity-gregory commented on __tests__/app.test.js
> +        .get("/api/articles/1")
You are requesting article 1, but expecting literally anything. How does this test give me and you confidence that your query is correct?

2023-11-20 16:50 UTC, nc-verity-gregory commented on api/models/topics-models.js
> +    if (!Number(article_id)){
PSQL will handle this, you do not need to promise reject. The database is specifically looking for a number, if you do not provide one you will get a 22P02 error which you should be handling.

2023-11-20 16:50 UTC, nc-verity-gregory commented on api/models/topics-models.js
> +    queryString += `WHERE article_id = ${article_id} ;`
This should absolutely not be in template literals, this leaves you open for SQL injection.

2023-11-21 08:41 UTC, nc-mick-fay commented on __tests__/app.test.js
> +            expect(selectedArticle).toEqual(articleOneCopy)
Good change to this testing to be more specific in your expected response

2023-11-21 08:43 UTC, nc-mick-fay commented on __tests__/app.test.js
> +    it("GET 404 when given article_id is not found in database", () => {
These small changes to test descriptions make it much easier to understand what you are testing for, good work!

2023-11-21 08:45 UTC, nc-mick-fay commented on api/errors.js
> +    res.status(500).send({ msg: 'Internal Server Error' });
Good additions of psql error handling and a general server error handler

2023-11-21 08:55 UTC, nc-mick-fay commented on api/models/topics-models.js
> +    .query(queryString, [article_id])
Good parameterisation of your query to avoid SQL injection!

2023-11-21 08:57 UTC, nc-mick-fay commented on api/controllers/topics-controllers.js
> -    .catch(next)
As you're sending back a pre-built JSON object, I suppose a catch block isn't strictly necessary here

2023-11-21 08:57 UTC, nc-mick-fay approved these changes
Much improved test descriptions, and I can see positive changes in all requested areas

2023-11-21 10:26 UTC, merged